services:
  shorty:
    container_name: dnr-shorty
    build: .
    env_file:
      - path: ./.env
        required: true
    networks:
      - mongo
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.shorty.entrypoints=websecure
      - traefik.http.routers.shorty.tls=true
      - traefik.http.routers.shorty.rule=Host("s.dnratthee.me")
      - traefik.http.services.shorty.loadbalancer.server.port=8080
    restart: always

networks:
  mongo:
    external: true
  web:
    external: true
